a = input("Enter the value of a: ")
print("The data type of a before typecasting is ", type(a))
a = int(a)
print("The data type of a after typecasting is ", type(a))
b = input("Enter the value of b: ")
print("The data type of b before typecasting is ", type(b))
b = int(b)
print("The data type of b after typecasting is ", type(b))
res = a + b
print("The sum of a + b is: ", res)